### ISSUE TITLE
Sticky window no Alt+Tab

### ISSUE THREAD

**Issue by sverhagen** [cspotcode/virtual-desktop-grid-switcher#1]
Sticky windows don't appear in the Alt+Tab sequence anymore.

**Comment by cspotcode** [comment]
I didn't modify this functionality at all, so it's from vanilla Virtual Desktop Grid Manager.

It's setting the extended window style WS_EX_TOOLWINDOW ([docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ff700543%28v=vs.85%29.aspx)), which apparently makes it appear on all desktops.  Positives are that it's Windows 10 native functionality.  I don't know if there's another native way to make a window appear on all desktops.

**Comment by cspotcode** [comment]
I prototyped a quick solution.  Instead of setting WS_EX_TOOLWINDOW, we add sticky windows to a list, and every time we switch desktops, we manually move all the sticky windows to the new desktop so that they remain visible.
- [ ] Detect when desktop is switched by Win+Tab, another app, or an off-desktop window gaining focus; move sticky windows
  - Looks like it already has code to detect desktop changes, since that's what it uses to update its own tray icon.

**Comment by sverhagen** [comment]
Thank you. Is that something that would be available to test, it's unclear if you made a commit and a release for this, as you don't yet seem to be linking issues and commits :wink: But guessing from the dates I'm seeing, this is not available yet?

**Comment by cspotcode** [comment]
Haha yes, I doubt I'll ever be disciplined enough to link issues and commits in this project.  I'll reply to this issue once it's implemented in a release.

A partial solution is in this commit (but no release yet): https://github.com/cspotcode/virtual-desktop-grid-switcher/commit/8f9fbd013b87868e28adaf6f4a9122b6f9959a70

However, it doesn't move sticky windows when a desktop switch is triggered externally.  I think I can handle that in [VirtualDesktop_CurrentChanged](https://github.com/cspotcode/virtual-desktop-grid-switcher/blob/master/VirtualDesktopGridSwitcher/VirtualDesktopGridManager.cs#L133), which gets called every time the desktop changes.

**Comment by cspotcode** [comment]
I just released a new version that implements the new sticky windows behavior.  You can try it out and see if it works for you.
https://github.com/cspotcode/virtual-desktop-grid-switcher/releases/tag/v4.0.0-beta1
