### ISSUE TITLE
Request: Switch Directly to a desktop

### ISSUE THREAD

**Issue by seraasch** [cspotcode/virtual-desktop-grid-switcher#2]
[edit]  I found it!

Suggestion: remove the text in the readme.md that says to ask for this feature  :)

Suggestion: add to the docs that CTRL+ALT is necessary with the Fn key to use this control.

Thanks!!!

**Comment by cspotcode** [comment]
I actually have never used this feature and I don't think I've implemented AutoHotKey integration for it; that's why the README says it's not implemented yet.  Using the exe's keybindings works, but they're not customizable.

**Comment by seraasch** [comment]
Yeah, I don't see anything in the autohotkey script for it, but I think I
can adapt to the existing bindings :)

**Comment by cspotcode** [comment]
I've implemented all the F1-F12 hotkeys in autohotkey; it'll be in the next release.  I updated the README to list them as well.
